name: Code Scan & Tests

on:
  push:
    branches:
      - main
      - master
  
  pull_request:
    branches:
      - main
      - master

jobs:
  analyze_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.12'  # or specify version e.g. 3.7.0

    - name: Flutter analyze (lint)
      run: flutter analyze

    - name: Flutter test
      run: flutter test --no-test-assets
